version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order-service:
    build:
      context: .
      dockerfile: order_service/Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq

  payment-service:
    build:
      context: .
      dockerfile: payment_service/Dockerfile
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq

  inventory-service:
    build:
      context: .
      dockerfile: inventory_service/Dockerfile
    ports:
      - "8003:8000"
    depends_on:
      - rabbitmq

  federated-server:
    build:
      context: ./federated
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    depends_on:
      - rabbitmq
